# Generated by Django 5.2 on 2025-04-20 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shaarpy", "0007_alter_links_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="links",
            options={
                "ordering": ["-sticky", "-date_created"],
                "permissions": (("view_private_links", "Can view private links"),),
                "verbose_name_plural": "Links",
            },
        ),
    ]
